# Generated by Django 5.1 on 2024-08-25 02:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="published_data",
            new_name="published_date",
        ),
    ]
